// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMYeof4O19efNJ0SwI8UyiKGeTnqbfSk',
    appId: '1:103010810593:web:0d94505efcfe8f945255a0',
    messagingSenderId: '103010810593',
    projectId: 'melofy01',
    authDomain: 'melofy01.firebaseapp.com',
    storageBucket: 'melofy01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3ccYjua4TMfPZUHsh44DP4DKqaQHkWk',
    appId: '1:103010810593:android:91d58bb2f68741fd5255a0',
    messagingSenderId: '103010810593',
    projectId: 'melofy01',
    storageBucket: 'melofy01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3lGQxj--Y4JrzTaYk2d23mcsoNV5WwE',
    appId: '1:103010810593:ios:fea978d1edbf429c5255a0',
    messagingSenderId: '103010810593',
    projectId: 'melofy01',
    storageBucket: 'melofy01.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu3lGQxj--Y4JrzTaYk2d23mcsoNV5WwE',
    appId: '1:103010810593:ios:fea978d1edbf429c5255a0',
    messagingSenderId: '103010810593',
    projectId: 'melofy01',
    storageBucket: 'melofy01.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGMYeof4O19efNJ0SwI8UyiKGeTnqbfSk',
    appId: '1:103010810593:web:b98c341a6231b9685255a0',
    messagingSenderId: '103010810593',
    projectId: 'melofy01',
    authDomain: 'melofy01.firebaseapp.com',
    storageBucket: 'melofy01.firebasestorage.app',
  );
}
